### PR TITLE
Add case for edge case behaviour of packHalf2x16

### PR DESCRIPTION
**Pull request by dneto0**

### CODE REVIEW

**Review by dj2 — APPROVED** [review]
LGTM, but I'm not sure if this will end up running as part of the CTS if that's your intention.

**Comment by dneto0** [comment]
I'm not intending this to be included in a CTS, not in this form anyway.  I mainly wanted a place to stash this interesting test case.

**Comment by asuonpaa** [comment]
Do we still want to keep this open?

**Comment by dneto0** [comment]
> Do we still want to keep this open?

I converted it to draft.  I'm referencing it from WebGPU CTS as an interesting case.

**Comment by dj2** [comment]
Can we close the PR? I believe as long as you don't delete the branch it should still be accessible from the URL you used in the link, but it will remove it from the amber PR list which makes it a lot clearer it won't be landing.

**Pull request closed without merging**
