### PR TITLE
Reproduction for webgpu cts atomic operation failure on mobile gpus (mali, adreno)

### PR DESCRIPTION
**Pull request by petermcneeleychromium**
This very simple amber file demonstrates a repo of the bug in webgpu CTS atomicAdd

This test was manually run on a mali (pixel 6) and it outputs the value 8 rather than 10.
Incorrect behavior appears to be that the shader is only executed on one thread (instead of 3).

crbug.com/42241359

### CODE REVIEW

**Comment by petermcneeleychromium** [comment]
Are you concerned about a pollution of Amber test cases with bug reproductions?

**Comment by dj2** [comment]
No, just more that this seems like the kind of thing that isn't betting tested by the Vulkan CTS, but probably should be. So it would be nice to have this in the CTS so it doesn't slip into other drivers/releases.

**Comment by petermcneeleychromium** [comment]
That makes sense. I was really just doing this PR as a way of saving my work and making it publicly available.

**Comment by petermcneeleychromium** [comment]
This test is in the process of being added to vk cts.

**Pull request closed without merging**
