### PR TITLE
Add support for Vulkan 1.4

### PR DESCRIPTION
**Pull request by lordalcol**

### CODE REVIEW

**Review by dj2 — APPROVED** [review]

**Comment by lordalcol** [comment]
@gfxstrand Since you were the original author of this, could you help replying and amending if needed?

**Comment by dj2** [comment]
The change looks good to me, just need to see if the bots are happy with it.

**Comment by lordalcol** [comment]
> The change looks good to me, just need to see if the bots are happy with it.

What about that other comment you left, that constrains uint8 to Vulkan 1.4?

**Comment by dj2** [comment]
Either I mis-read the other PR, or this one is different because it does do an `if vk1.4 {} else { old thing }`

**Comment by dj2** [comment]
(looking again, I mis-read the other PR, heh)

**Comment by lordalcol** [comment]
Builds failed. I'll take a look at what is needed to fix.

**Comment by lordalcol** [comment]
I have a feeling it may need a Vulkan headers update. Not sure how to do it here.

**Comment by dj2** [comment]
Change the sha in the `vulkan_headers_revision` in the `DEPS` file.

**Comment by dj2** [comment]
I'm guessing you're going to need to do all the vulkan libraries as they tend to be intertwined.

**Comment by lordalcol** [comment]
> I'm guessing you're going to need to do all the vulkan libraries as they tend to be intertwined.

Yes, I'm doing them all now, checking locally too.

**Comment by dj2** [comment]
Merged. Thanks a lot for the fixes.

**Pull request merged**
