### PR TITLE
[WIP] Adding CLSPV support

### LINKED ISSUE #429: Compile and build CLSPV in Amber
Add CLSPV to the third_party in amber and hookup the build. This should be an optional component that is off by default.

### PR DESCRIPTION
**Pull request by dj2**
This CL adds the necessary code to build CLSPV as part of the Amber
build.

Fixes #429

### CODE REVIEW

**Comment by dj2** [comment]
This is marked as WIP because it requires a patch to LLVM in order to build. I see no way of getting this to work otherwise. It seems that even with testing disabled in LLVM the LLVMTestingSupport library is being created. But, if testing is disabled then gtest isn't available and configure fails.

```
diff --git a/lib/CMakeLists.txt b/lib/CMakeLists.txt
index c458927e3cd..34f78cb4398 100644
--- a/lib/CMakeLists.txt
+++ b/lib/CMakeLists.txt
@@ -27,5 +27,7 @@ add_subdirectory(Passes)
 add_subdirectory(TextAPI)
 add_subdirectory(ToolDrivers)
 add_subdirectory(XRay)
-add_subdirectory(Testing)
+if (${LLVM_INCLUDE_TESTING})
+  add_subdirectory(Testing)
+endif()
 add_subdirectory(WindowsManifest)
```

**Comment by dj2** [comment]
@alan-baker  fyi

**Comment by dj2** [comment]
Oh, this also needs a CLSPV patch, which I'll push up.

**Comment by dj2** [comment]
https://github.com/google/clspv/pull/374

**Comment by alan-baker** [comment]
FYI https://reviews.llvm.org/D63097 is for the LLVM patch.

**Comment by alan-baker** [comment]
Subsumed by #574

**Pull request closed without merging**
