### PR TITLE
docs: Fix compute shader example

### PR DESCRIPTION
**Pull request by Flakebi**
The expect lines in the example compare to integer values but the shader wrote float values into the buffer, making the test fail. Write integer values in the shader to make it pass.

### CODE REVIEW

**Comment by Flakebi** [comment]
friendly ping for review

**Comment by dj2** [comment]
You'll need to sign the CLA (the bot is currently unhappy) before this can be reviewed/accepted.

**Comment by Flakebi** [comment]
Hm, I did and restarted as it was written in the help. The `cla/google` action also shows a green checkmark. Is there anything more I need to do?
Thanks for the fast reply!

**Review by dj2 — APPROVED** [review]

**Comment by dj2** [comment]
Apologies, I saw the comment above and missed the green checkmark. I've updated the PR and kicked off the bots so the required checks will run. I'll merge afterwards.

Thank you for your contribution and your patience.

**Comment by dj2** [comment]
Bot failure is a flake, this doesn't actually change functionality so landing.

**Pull request merged**
