### PR TITLE
Avoid implicit conversion of size_t to double

### PR DESCRIPTION
**Pull request by dneto0**

### CODE REVIEW

**Comment by dneto0** [comment]
For the first issue in #628

**Comment by dneto0** [comment]
cc: @ben-clayton

**Comment by ben-clayton** [comment]
LGTM, thanks!

**Comment by dneto0** [comment]
Waiting for bots... kokoro is slow to start these days...

**Comment by dneto0** [comment]
Superceded by https://github.com/google/amber/pull/634

**Pull request closed without merging**
